Wanted but not invoked:
cacheAdvice.publishCacheMetrics(
    mockPjp,
    "failure"
);
-> at com.personalcapital.cache.aop.PcapMultiCacheableAdvice.publishCacheMetrics(PcapMultiCacheableAdvice.java:45)

However, there was exactly 1 interaction with this mock:
cacheAdvice.doMultiCacheable(
    mockPjp,
    mockAnnotation
);
-> at com.personalcapital.cache.aop.ExceptionTest.lambda$testCacheFailureAndEvictionFailureMetrics$0(ExceptionTest.java:51)


Wanted but not invoked:
cacheAdvice.publishCacheMetrics(
    mockPjp,
    "failure"
);
-> at com.personalcapital.cache.aop.PcapMultiCacheableAdvice.publishCacheMetrics(PcapMultiCacheableAdvice.java:45)

However, there was exactly 1 interaction with this mock:
cacheAdvice.doMultiCacheable(
    mockPjp,
    mockAnnotation
);
-> at com.personalcapital.cache.aop.ExceptionTest.lambda$testCacheFailureAndEvictionFailureMetrics$0(ExceptionTest.java:51)


	at com.personalcapital.cache.aop.PcapMultiCacheableAdvice.publishCacheMetrics(PcapMultiCacheableAdvice.java:45)
	at com.personalcapital.cache.aop.ExceptionTest.testCacheFailureAndEvictionFailureMetrics(ExceptionTest.java:54)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


Process finished with exit code 255
